#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=728890689407
BundleId=com.unit9.swip3wear
ClientId=728890689407-pvcpij38qgep32703e1ukn6h4emjve1f.apps.googleusercontent.com

*/

#define kAppID "728890689407"
#define kBundleID "com.unit9.swip3wear"
#define kClientID "728890689407-pvcpij38qgep32703e1ukn6h4emjve1f.apps.googleusercontent.com"

#endif


